-keep class com.nanu.aitradingbot.** { *; }
-keep class net.i2p.crypto.eddsa.** { *; }
-keep class org.web3j.** { *; }
-dontwarn org.web3j.**
-dontwarn net.i2p.**
-dontwarn okhttp3.**
-dontwarn okio.**
